version: "3"
services:
  backend:
    restart: always
    container_name: backend
    build: ./backend
    expose:
      - 5000
    volumes:
      - ./backend:/code/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1