version: "3"

services:

  backend:
    container_name: backend
    restart: always
    build: backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/code
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1

  frontend:
    container_name: frontend
    restart: always
    # https://github.com/facebook/create-react-app/issues/8688
    stdin_open: true
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/code